// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQhtVcQKB0zrSFi0YIaUxpivij8jV_3A',
    appId: '1:713427915567:web:cc292abb0b0fedcd3707da',
    messagingSenderId: '713427915567',
    projectId: 'chatapp-691ab',
    authDomain: 'chatapp-691ab.firebaseapp.com',
    storageBucket: 'chatapp-691ab.firebasestorage.app',
    measurementId: 'G-YP0BYDC72E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN500MZIlyU3HRp3q1rJ83Xa9bCjL1a5A',
    appId: '1:713427915567:android:25f5b862906094193707da',
    messagingSenderId: '713427915567',
    projectId: 'chatapp-691ab',
    storageBucket: 'chatapp-691ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnI2oYW8PQSRmHfJ2jNEBnLYQjZpYw70',
    appId: '1:713427915567:ios:b2d8b7a44678a12d3707da',
    messagingSenderId: '713427915567',
    projectId: 'chatapp-691ab',
    storageBucket: 'chatapp-691ab.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnI2oYW8PQSRmHfJ2jNEBnLYQjZpYw70',
    appId: '1:713427915567:ios:b2d8b7a44678a12d3707da',
    messagingSenderId: '713427915567',
    projectId: 'chatapp-691ab',
    storageBucket: 'chatapp-691ab.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQhtVcQKB0zrSFi0YIaUxpivij8jV_3A',
    appId: '1:713427915567:web:08bd3034a11f55153707da',
    messagingSenderId: '713427915567',
    projectId: 'chatapp-691ab',
    authDomain: 'chatapp-691ab.firebaseapp.com',
    storageBucket: 'chatapp-691ab.firebasestorage.app',
    measurementId: 'G-4FJSXN12WW',
  );
}
